version: "3.8"
services:
  frontend:
    image: asanalii/vue-frontend:latest
    deploy:
      placement:
        constraints: [node.hostname == swarm-node-1]
    networks:
      - app-net

  backend:
    image: asanalii/fastapi-backend:latest
    environment:
      - MONGO_URI=mongodb+srv://testa:asan1234@test.wr2lcrn.mongodb.net/?retryWrites=true&w=majority&appName=test&tls=true&tlsAllowInvalidCertificates=true
    deploy:
      placement:
        constraints: [node.hostname == swarm-node-2]
    networks:
      - app-net

networks:
  app-net:
    driver: overlay
